```{r}
#| echo: false
#| message: false
#| warning: false

library(leaflet)
library(magrittr)

# Carichiamo il database
conferenze <- read.csv("conferenze_db.csv", stringsAsFactors = FALSE)

# Forziamo le coordinate a numeri
conferenze$lat <- as.numeric(conferenze$lat)
conferenze$lng <- as.numeric(conferenze$lng)

# Pulizia: rimuoviamo righe con coordinate mancanti
conferenze <- conferenze[!is.na(conferenze$lat) & !is.na(conferenze$lng), ]

# Palette colori aggiornata (Set3 è ottima per molte categorie diverse)
pal <- colorFactor(palette = "Set3", domain = conferenze$type)

leaflet(conferenze) %>%
  addTiles() %>%
  addCircleMarkers(
    ~lng, ~lat, 
    popup = ~paste0("<b>", event_name, "</b><br>", 
                   name, " - ", city, "<br>",
                   "<i>", type, "</i>"),
    color = ~pal(type),
    fillOpacity = 0.8,
    radius = 10,
    stroke = TRUE,
    weight = 1
  ) %>%
  addLegend(pal = pal, values = ~type, title = "Activity Type", position = "bottomright")
```
### Lista delle Conferenze

```{r}
#| echo: false
knitr::kable(conferenze[, c("event_name","name", "city", "type")], col.names = c("Event", "Venue", "City", "Type"))
```